title: Samuel Fox # your name (or website title) here
#logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior in college currently working on a bachelor's degree in computer science with a focus on simulation and game programming. I have always had a passion for games and am hoping to share that passion by making my own games.
  <br><br>
  <a href="https://www.linkedin.com/in/samuel-fox-618750196/">View My LinkedIn Profile</a> 
  <br><br>
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
